# Generated by Django 5.0.3 on 2024-03-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GivingWay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationpic',
            field=models.FileField(null=True, upload_to='donationpic/'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorpic',
            field=models.ImageField(null=True, upload_to='donorpic/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='idpic',
            field=models.FileField(null=True, upload_to='volunteerid/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteerpic',
            field=models.ImageField(null=True, upload_to='volunteer/'),
        ),
    ]
