# Generated by Django 5.0.3 on 2024-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GivingWay', '0002_alter_donation_donationpic_alter_donor_donorpic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
