# Generated by Django 5.0.3 on 2024-04-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GivingWay', '0004_alter_volunteer_adminremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='adminremark',
            field=models.CharField(max_length=20),
        ),
    ]
