# Generated by Django 5.0.3 on 2024-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GivingWay', '0006_remove_volunteer_adminremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteerpic',
            field=models.FileField(null=True, upload_to='volunteer/'),
        ),
    ]
