# Generated by Django 5.0.3 on 2024-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GivingWay', '0007_alter_volunteer_volunteerpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
